package ht.wt.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ht.wt.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 21:12:36 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PaivaTest {



  // Generated by ComTest BEGIN
  /** testToString153 */
  @Test
  public void testToString153() {    // Paiva: 153
    Paiva paiva = new Paiva(); 
    paiva.parse("3  |    12.3.2020   |   Orivesi       |  07:18"); 
    assertEquals("From: Paiva line: 156", true, paiva.toString().startsWith("3|12.3.2020|Orivesi|07:18|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi246 */
  @Test
  public void testRekisteroi246() {    // Paiva: 246
    Paiva paiva1 = new Paiva(); 
    assertEquals("From: Paiva line: 248", 0, paiva1.getTunnusNro()); 
    paiva1.rekisteroi(); 
    Paiva paiva2 = new Paiva(); 
    paiva2.rekisteroi(); 
    int n1 = paiva1.getTunnusNro(); 
    int n2 = paiva2.getTunnusNro(); 
    assertEquals("From: Paiva line: 254", n2-1, n1); 
  } // Generated by ComTest END
}