package ht.wt.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ht.wt.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 21:15:52 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class SaatilaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi38 */
  @Test
  public void testRekisteroi38() {    // Saatila: 38
    Paiva paiva1 = new Paiva(); 
    assertEquals("From: Saatila line: 40", 0, paiva1.getTunnusNro()); 
    paiva1.rekisteroi(); 
    Paiva paiva2 = new Paiva(); 
    paiva2.rekisteroi(); 
    int n1 = paiva1.getTunnusNro(); 
    int n2 = paiva2.getTunnusNro(); 
    assertEquals("From: Saatila line: 46", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString60 */
  @Test
  public void testToString60() {    // Saatila: 60
    Saatila saa = new Saatila(""); 
    saa.parse("3  |    aurinkoinen"); 
    assertEquals("From: Saatila line: 63", true, saa.toString().startsWith("3|aurinkoinen|")); 
  } // Generated by ComTest END
}